Tweak the async README section
ChimeHQ/ConcurrencyPlus pull request #5
Opened 2022-08-28 10:32 UTC by DivineDominion

Found a typo ("Mmethod") and missing `func`s, so I tried to smooth things over. Used trailing closures without parens because the rest of the README doesn't wrap it in parens, either. Please do pick nits if something doesn't look right :)

2022-08-28 11:12 UTC, mattmassicotte requested changes

2022-08-28 11:12 UTC, mattmassicotte commented on README.md
> +You might be tempted to make your XPC interface functions `async`. This does not handle connection failures and can hang your `Task`s because it violates the Structured Concurrency contract, so it is
What do you think about scoping the link just to the "ExtensionKit and XPC" part?

2022-08-29 10:56 UTC, merged

2022-08-30 06:25 UTC, DivineDominion commented
Sorry for the slow response :)

2022-08-30 18:50 UTC, mattmassicotte commented
Oh absolutely no need to apologize! Just didn't want to make you do it. Thanks for the submission!